-- ============================================================================
-- 50 fish (`poisson`) + 50 shellfish & crustaceans (`crustaces`).
-- ON CONFLICT keeps the migration idempotent against the existing catalogue.
-- ============================================================================

insert into public.ingredient (ingredient_name, ingredient_default_unit, ingredient_type)
values
  -- ----------- POISSONS (50) -----------
  ('Saumon',                    'g',     'poisson'),
  ('Saumon fumé',               'g',     'poisson'),
  ('Truite',                    'piece', 'poisson'),
  ('Truite saumonée',           'piece', 'poisson'),
  ('Truite arc-en-ciel',        'piece', 'poisson'),
  ('Thon',                      'g',     'poisson'),
  ('Thon rouge',                'g',     'poisson'),
  ('Thon blanc germon',         'g',     'poisson'),
  ('Cabillaud',                 'g',     'poisson'),
  ('Morue salée',               'g',     'poisson'),
  ('Lieu noir',                 'g',     'poisson'),
  ('Lieu jaune',                'g',     'poisson'),
  ('Merlu',                     'g',     'poisson'),
  ('Colin',                     'g',     'poisson'),
  ('Églefin',                   'g',     'poisson'),
  ('Haddock fumé',              'g',     'poisson'),
  ('Bar',                       'piece', 'poisson'),
  ('Loup de mer',               'piece', 'poisson'),
  ('Dorade royale',             'piece', 'poisson'),
  ('Dorade grise',              'piece', 'poisson'),
  ('Daurade',                   'piece', 'poisson'),
  ('Sole',                      'piece', 'poisson'),
  ('Plie',                      'piece', 'poisson'),
  ('Limande',                   'piece', 'poisson'),
  ('Carrelet',                  'piece', 'poisson'),
  ('Turbot',                    'piece', 'poisson'),
  ('Sardine',                   'piece', 'poisson'),
  ('Anchois',                   'piece', 'poisson'),
  ('Maquereau',                 'piece', 'poisson'),
  ('Hareng',                    'piece', 'poisson'),
  ('Hareng fumé',               'piece', 'poisson'),
  ('Espadon',                   'g',     'poisson'),
  ('Lotte',                     'g',     'poisson'),
  ('Raie',                      'piece', 'poisson'),
  ('Saint-Pierre',              'piece', 'poisson'),
  ('Rouget',                    'piece', 'poisson'),
  ('Rouget barbet',             'piece', 'poisson'),
  ('Grondin',                   'piece', 'poisson'),
  ('Mérou',                     'g',     'poisson'),
  ('Tilapia',                   'piece', 'poisson'),
  ('Pangasius',                 'piece', 'poisson'),
  ('Brochet',                   'piece', 'poisson'),
  ('Sandre',                    'piece', 'poisson'),
  ('Perche',                    'piece', 'poisson'),
  ('Carpe',                     'piece', 'poisson'),
  ('Anguille',                  'g',     'poisson'),
  ('Congre',                    'g',     'poisson'),
  ('Mulet',                     'piece', 'poisson'),
  ('Maigre',                    'piece', 'poisson'),
  ('Vivaneau',                  'piece', 'poisson'),

  -- ----------- CRUSTACÉS & FRUITS DE MER (50) -----------
  -- Crustacés stricto sensu
  ('Crevette rose',             'g',     'crustaces'),
  ('Crevette grise',            'g',     'crustaces'),
  ('Crevette tigrée',           'g',     'crustaces'),
  ('Gambas',                    'piece', 'crustaces'),
  ('Crevette blanche',          'g',     'crustaces'),
  ('Crevette japonaise',        'g',     'crustaces'),
  ('Crevette nordique',         'g',     'crustaces'),
  ('Langoustine',               'piece', 'crustaces'),
  ('Homard',                    'piece', 'crustaces'),
  ('Homard bleu',               'piece', 'crustaces'),
  ('Homard canadien',           'piece', 'crustaces'),
  ('Langouste',                 'piece', 'crustaces'),
  ('Langouste rose',            'piece', 'crustaces'),
  ('Crabe',                     'piece', 'crustaces'),
  ('Crabe tourteau',            'piece', 'crustaces'),
  ('Crabe araignée',            'piece', 'crustaces'),
  ('Crabe royal',               'piece', 'crustaces'),
  ('Crabe dormeur',             'piece', 'crustaces'),
  ('Crabe vert',                'piece', 'crustaces'),
  ('Étrille',                   'piece', 'crustaces'),
  ('Bouquet',                   'g',     'crustaces'),
  ('Écrevisse',                 'piece', 'crustaces'),
  ('Cigale de mer',             'piece', 'crustaces'),
  ('Squille',                   'piece', 'crustaces'),

  -- Bivalves
  ('Moule',                     'g',     'crustaces'),
  ('Moule de bouchot',          'g',     'crustaces'),
  ('Moule d''Espagne',          'g',     'crustaces'),
  ('Huître',                    'piece', 'crustaces'),
  ('Huître creuse',             'piece', 'crustaces'),
  ('Huître plate',              'piece', 'crustaces'),
  ('Palourde',                  'g',     'crustaces'),
  ('Coque',                     'g',     'crustaces'),
  ('Praire',                    'g',     'crustaces'),
  ('Coquille Saint-Jacques',    'piece', 'crustaces'),
  ('Pétoncle',                  'g',     'crustaces'),
  ('Amande de mer',             'g',     'crustaces'),
  ('Telline',                   'g',     'crustaces'),
  ('Couteau',                   'piece', 'crustaces'),
  ('Vernis',                    'g',     'crustaces'),

  -- Gastéropodes
  ('Bigorneau',                 'g',     'crustaces'),
  ('Bulot',                     'g',     'crustaces'),
  ('Patelle',                   'g',     'crustaces'),
  ('Ormeau',                    'piece', 'crustaces'),

  -- Céphalopodes
  ('Poulpe',                    'g',     'crustaces'),
  ('Calamar',                   'g',     'crustaces'),
  ('Encornet',                  'g',     'crustaces'),
  ('Seiche',                    'g',     'crustaces'),
  ('Supion',                    'g',     'crustaces'),

  -- Autres
  ('Oursin',                    'piece', 'crustaces'),
  ('Pousse-pied',               'g',     'crustaces')
on conflict (lower(ingredient_name)) do nothing;
