-- ============================================================================
-- Ingredient catalogue — round 2. Continuation of 081 (separate migration with
-- a higher number so `db push` applies it in order). Idempotent: `on conflict
-- do nothing` skips anything already seeded — the 081 rows below are re-listed
-- and simply skipped. Append NEW ingredients at the end of the VALUES list.
-- ============================================================================

insert into public.ingredient (ingredient_name, ingredient_default_unit, ingredient_type)
values
  -- Légumes
  ('Carotte',                   'piece', 'legumes'),
  ('Pomme de terre',            'g',     'legumes'),
  ('Oignon',                    'piece', 'legumes'),
  ('Oignon rouge',              'piece', 'legumes'),
  ('Échalote',                  'piece', 'legumes'),
  ('Ail',                       'gousse','legumes'),
  ('Poireau',                   'piece', 'legumes'),
  ('Courgette',                 'piece', 'legumes'),
  ('Aubergine',                 'piece', 'legumes'),
  ('Poivron rouge',             'piece', 'legumes'),
  ('Poivron vert',              'piece', 'legumes'),
  ('Poivron jaune',             'piece', 'legumes'),
  ('Tomate',                    'piece', 'legumes'),
  ('Tomate cerise',             'g',     'legumes'),
  ('Concombre',                 'piece', 'legumes'),
  ('Salade verte',              'piece', 'legumes'),
  ('Épinard',                   'g',     'legumes'),
  ('Brocoli',                   'g',     'legumes'),
  ('Chou-fleur',                'g',     'legumes'),
  ('Chou vert',                 'g',     'legumes'),
  ('Chou rouge',                'g',     'legumes'),
  ('Chou de Bruxelles',         'g',     'legumes'),
  ('Haricot vert',              'g',     'legumes'),
  ('Petit pois',                'g',     'legumes'),
  ('Maïs',                      'g',     'legumes'),
  ('Betterave',                 'piece', 'legumes'),
  ('Navet',                     'piece', 'legumes'),
  ('Céleri',                    'g',     'legumes'),
  ('Fenouil',                   'piece', 'legumes'),
  ('Radis',                     'botte', 'legumes'),
  ('Courge butternut',          'g',     'legumes'),
  ('Potiron',                   'g',     'legumes'),
  ('Patate douce',              'g',     'legumes'),
  ('Endive',                    'piece', 'legumes'),
  ('Asperge',                   'botte', 'legumes'),
  ('Artichaut',                 'piece', 'legumes'),
  ('Blette',                    'g',     'legumes'),
  ('Roquette',                  'g',     'legumes'),

  -- Fruits
  ('Pomme',                     'piece', 'fruits'),
  ('Poire',                     'piece', 'fruits'),
  ('Banane',                    'piece', 'fruits'),
  ('Orange',                    'piece', 'fruits'),
  ('Citron vert',               'piece', 'fruits'),
  ('Fraise',                    'g',     'fruits'),
  ('Framboise',                 'g',     'fruits'),
  ('Myrtille',                  'g',     'fruits'),
  ('Raisin',                    'g',     'fruits'),
  ('Pêche',                     'piece', 'fruits'),
  ('Abricot',                   'piece', 'fruits'),
  ('Cerise',                    'g',     'fruits'),
  ('Ananas',                    'piece', 'fruits'),
  ('Mangue',                    'piece', 'fruits'),
  ('Kiwi',                      'piece', 'fruits'),
  ('Melon',                     'piece', 'fruits'),
  ('Pastèque',                  'g',     'fruits'),
  ('Pamplemousse',              'piece', 'fruits'),
  ('Clémentine',                'piece', 'fruits'),
  ('Figue',                     'piece', 'fruits'),
  ('Prune',                     'piece', 'fruits'),
  ('Avocat',                    'piece', 'fruits'),

  -- Champignons
  ('Champignon de Paris',       'g',     'champignons'),
  ('Cèpe',                      'g',     'champignons'),
  ('Girolle',                   'g',     'champignons'),
  ('Pleurote',                  'g',     'champignons'),
  ('Shiitaké',                  'g',     'champignons'),

  -- Viande
  ('Filet de poulet',           'g',     'viande'),
  ('Cuisse de poulet',          'piece', 'viande'),
  ('Escalope de dinde',         'g',     'viande'),
  ('Lardons',                   'g',     'viande'),
  ('Jambon blanc',              'tranche','viande'),
  ('Saucisse',                  'piece', 'viande'),
  ('Chipolata',                 'piece', 'viande'),
  ('Merguez',                   'piece', 'viande'),
  ('Saucisson',                 'g',     'viande'),
  ('Côtelette d''agneau',       'piece', 'viande'),
  ('Gigot d''agneau',           'g',     'viande'),
  ('Steak haché',               'piece', 'viande'),
  ('Magret de canard',          'piece', 'viande'),
  ('Bacon',                     'tranche','viande'),
  ('Escalope de veau',          'g',     'viande'),
  ('Côte de porc',              'piece', 'viande'),
  ('Rôti de porc',              'g',     'viande'),
  ('Cuisse de canard',          'piece', 'viande'),

  -- Poisson
  ('Saumon',                    'g',     'poisson'),
  ('Cabillaud',                 'g',     'poisson'),
  ('Thon',                      'g',     'poisson'),
  ('Truite',                    'g',     'poisson'),
  ('Dorade',                    'piece', 'poisson'),
  ('Bar',                       'piece', 'poisson'),
  ('Maquereau',                 'piece', 'poisson'),
  ('Sardine',                   'g',     'poisson'),
  ('Lieu noir',                 'g',     'poisson'),
  ('Colin',                     'g',     'poisson'),
  ('Sole',                      'piece', 'poisson'),
  ('Saumon fumé',               'tranche','poisson'),

  -- Crustacés & fruits de mer
  ('Crevette',                  'g',     'crustaces'),
  ('Gambas',                    'g',     'crustaces'),
  ('Moule',                     'g',     'crustaces'),
  ('Huître',                    'piece', 'crustaces'),
  ('Noix de Saint-Jacques',     'piece', 'crustaces'),
  ('Crabe',                     'g',     'crustaces'),
  ('Calamar',                   'g',     'crustaces'),
  ('Langoustine',               'g',     'crustaces'),

  -- Crémerie
  ('Lait entier',               'ml',    'cremerie'),
  ('Crème liquide',             'ml',    'cremerie'),
  ('Yaourt nature',             'piece', 'cremerie'),
  ('Fromage blanc',             'g',     'cremerie'),
  ('Mozzarella',                'g',     'cremerie'),
  ('Emmental râpé',             'g',     'cremerie'),
  ('Gruyère',                   'g',     'cremerie'),
  ('Comté',                     'g',     'cremerie'),
  ('Fromage de chèvre',         'g',     'cremerie'),
  ('Feta',                      'g',     'cremerie'),
  ('Ricotta',                   'g',     'cremerie'),
  ('Mascarpone',                'g',     'cremerie'),
  ('Beurre demi-sel',           'g',     'cremerie'),
  ('Crème de coco',             'ml',    'cremerie'),

  -- Boulangerie
  ('Baguette',                  'piece', 'boulangerie'),
  ('Pain de mie',               'tranche','boulangerie'),
  ('Pain complet',              'tranche','boulangerie'),
  ('Farine de blé',             'g',     'boulangerie'),
  ('Levure boulangère',         'sachet','boulangerie'),
  ('Levure chimique',           'sachet','boulangerie'),
  ('Pâte feuilletée',           'piece', 'boulangerie'),
  ('Pâte brisée',               'piece', 'boulangerie'),
  ('Pâte à pizza',              'piece', 'boulangerie'),
  ('Pain à burger',             'piece', 'boulangerie'),
  ('Tortilla',                  'piece', 'boulangerie'),
  ('Chapelure',                 'g',     'boulangerie'),

  -- Céréales & pâtes
  ('Riz blanc',                 'g',     'cereales'),
  ('Riz basmati',               'g',     'cereales'),
  ('Riz complet',               'g',     'cereales'),
  ('Pâtes',                     'g',     'cereales'),
  ('Spaghetti',                 'g',     'cereales'),
  ('Penne',                     'g',     'cereales'),
  ('Tagliatelle',               'g',     'cereales'),
  ('Macaroni',                  'g',     'cereales'),
  ('Semoule',                   'g',     'cereales'),
  ('Boulgour',                  'g',     'cereales'),
  ('Quinoa',                    'g',     'cereales'),
  ('Polenta',                   'g',     'cereales'),
  ('Flocons d''avoine',         'g',     'cereales'),
  ('Couscous',                  'g',     'cereales'),

  -- Féculents
  ('Gnocchi',                   'g',     'feculents'),
  ('Pâtes fraîches',            'g',     'feculents'),
  ('Raviolis',                  'g',     'feculents'),

  -- Légumineuses
  ('Lentilles vertes',          'g',     'legumineuses'),
  ('Lentilles corail',          'g',     'legumineuses'),
  ('Pois chiches',              'g',     'legumineuses'),
  ('Haricots rouges',           'g',     'legumineuses'),
  ('Haricots blancs',           'g',     'legumineuses'),
  ('Flageolets',                'g',     'legumineuses'),
  ('Fèves',                     'g',     'legumineuses'),
  ('Pois cassés',               'g',     'legumineuses'),

  -- Graines & fruits secs
  ('Amande',                    'g',     'graines'),
  ('Noix',                      'g',     'graines'),
  ('Noisette',                  'g',     'graines'),
  ('Pignon de pin',             'g',     'graines'),
  ('Graine de sésame',          'g',     'graines'),
  ('Graine de tournesol',       'g',     'graines'),
  ('Graine de courge',          'g',     'graines'),
  ('Graine de lin',             'g',     'graines'),
  ('Cacahuète',                 'g',     'graines'),
  ('Pistache',                  'g',     'graines'),
  ('Noix de cajou',             'g',     'graines'),
  ('Graine de chia',            'g',     'graines'),
  ('Raisin sec',                'g',     'graines'),

  -- Épicerie salée
  ('Bouillon cube',             'piece', 'epicerie_salee'),
  ('Sauce soja',                'ml',    'epicerie_salee'),
  ('Moutarde',                  'g',     'epicerie_salee'),
  ('Ketchup',                   'ml',    'epicerie_salee'),
  ('Mayonnaise',                'g',     'epicerie_salee'),
  ('Cornichon',                 'g',     'epicerie_salee'),
  ('Olive verte',               'g',     'epicerie_salee'),
  ('Olive noire',               'g',     'epicerie_salee'),
  ('Câpres',                    'g',     'epicerie_salee'),
  ('Thon en boîte',             'boite', 'epicerie_salee'),
  ('Maïs en boîte',             'boite', 'epicerie_salee'),
  ('Lait de coco',              'ml',    'epicerie_salee'),
  ('Pâte de curry',             'g',     'epicerie_salee'),
  ('Sauce tomate',              'g',     'epicerie_salee'),
  ('Pesto',                     'g',     'epicerie_salee'),
  ('Fond de veau',              'g',     'epicerie_salee'),
  ('Bouillon de légumes',       'piece', 'epicerie_salee'),

  -- Épicerie sucrée
  ('Sucre',                     'g',     'epicerie_sucree'),
  ('Sucre roux',                'g',     'epicerie_sucree'),
  ('Sucre vanillé',             'sachet','epicerie_sucree'),
  ('Sucre glace',               'g',     'epicerie_sucree'),
  ('Miel',                      'g',     'epicerie_sucree'),
  ('Confiture',                 'g',     'epicerie_sucree'),
  ('Chocolat noir',             'g',     'epicerie_sucree'),
  ('Chocolat au lait',          'g',     'epicerie_sucree'),
  ('Cacao en poudre',           'g',     'epicerie_sucree'),
  ('Pépites de chocolat',       'g',     'epicerie_sucree'),
  ('Extrait de vanille',        'ml',    'epicerie_sucree'),
  ('Sirop d''érable',           'ml',    'epicerie_sucree'),
  ('Pâte à tartiner',           'g',     'epicerie_sucree'),
  ('Compote',                   'g',     'epicerie_sucree'),
  ('Maïzena',                   'g',     'epicerie_sucree'),
  ('Lait concentré sucré',      'g',     'epicerie_sucree'),
  ('Crème de marron',           'g',     'epicerie_sucree'),

  -- Surgelé
  ('Épinards surgelés',         'g',     'surgele'),
  ('Petits pois surgelés',      'g',     'surgele'),
  ('Frites surgelées',          'g',     'surgele'),
  ('Poêlée de légumes surgelée','g',     'surgele'),
  ('Glace vanille',             'ml',    'surgele'),
  ('Poisson pané',              'piece', 'surgele'),
  ('Fruits rouges surgelés',    'g',     'surgele'),

  -- Boissons
  ('Eau',                       'ml',    'boissons'),
  ('Jus d''orange',             'ml',    'boissons'),
  ('Bière',                     'ml',    'boissons'),
  ('Cidre',                     'ml',    'boissons'),
  ('Café',                      'g',     'boissons'),
  ('Thé',                       'sachet','boissons'),
  ('Lait d''amande',            'ml',    'boissons'),
  ('Lait de soja',              'ml',    'boissons'),

  -- Condiments & épices
  ('Cumin',                     'g',     'condiments_epices'),
  ('Curry',                     'g',     'condiments_epices'),
  ('Paprika',                   'g',     'condiments_epices'),
  ('Curcuma',                   'g',     'condiments_epices'),
  ('Cannelle',                  'g',     'condiments_epices'),
  ('Noix de muscade',           'g',     'condiments_epices'),
  ('Gingembre',                 'g',     'condiments_epices'),
  ('Coriandre',                 'g',     'condiments_epices'),
  ('Persil',                    'botte', 'condiments_epices'),
  ('Basilic',                   'botte', 'condiments_epices'),
  ('Thym',                      'g',     'condiments_epices'),
  ('Romarin',                   'g',     'condiments_epices'),
  ('Laurier',                   'piece', 'condiments_epices'),
  ('Origan',                    'g',     'condiments_epices'),
  ('Menthe',                    'botte', 'condiments_epices'),
  ('Ciboulette',                'botte', 'condiments_epices'),
  ('Vinaigre balsamique',       'ml',    'condiments_epices'),
  ('Vinaigre de vin',           'ml',    'condiments_epices'),
  ('Huile de tournesol',        'ml',    'condiments_epices'),
  ('Huile de sésame',           'ml',    'condiments_epices'),
  ('Sauce worcestershire',      'ml',    'condiments_epices'),
  ('Piment',                    'piece', 'condiments_epices'),
  ('Clou de girofle',           'piece', 'condiments_epices'),
  ('Safran',                    'pincee','condiments_epices'),
  ('Bicarbonate de soude',      'g',     'condiments_epices'),

  -- Frais / traiteur
  ('Tofu',                      'g',     'frais_traiteur'),
  ('Houmous',                   'g',     'frais_traiteur'),
  ('Tzatziki',                  'g',     'frais_traiteur'),
  ('Surimi',                    'piece', 'frais_traiteur'),
  ('Tarama',                    'g',     'frais_traiteur'),

  -- Œuf : variante sans ligature, plus simple à taper au clavier
  ('Oeuf',                      'piece', 'cremerie'),

  -- Fromages (round 2)
  ('Camembert',                 'g',     'cremerie'),
  ('Brie',                      'g',     'cremerie'),
  ('Brie de Meaux',             'g',     'cremerie'),
  ('Roquefort',                 'g',     'cremerie'),
  ('Raclette',                  'g',     'cremerie'),
  ('Reblochon',                 'g',     'cremerie'),
  ('Cheddar',                   'g',     'cremerie'),
  ('Bleu d''Auvergne',          'g',     'cremerie'),
  ('Gorgonzola',                'g',     'cremerie'),
  ('Tomme de Savoie',           'g',     'cremerie'),
  ('Cantal',                    'g',     'cremerie'),
  ('Beaufort',                  'g',     'cremerie'),
  ('Burrata',                   'g',     'cremerie'),
  ('Boursin',                   'g',     'cremerie'),
  ('Munster',                   'g',     'cremerie'),
  ('Maroilles',                 'g',     'cremerie'),
  ('Morbier',                   'g',     'cremerie'),
  ('Saint-Nectaire',            'g',     'cremerie'),
  ('Pont-l''Évêque',            'g',     'cremerie'),
  ('Livarot',                   'g',     'cremerie'),
  ('Fromage de brebis',         'g',     'cremerie'),
  ('Chèvre frais',              'g',     'cremerie'),
  ('Bûche de chèvre',           'g',     'cremerie'),
  ('Crottin de Chavignol',      'piece', 'cremerie'),
  ('Saint-Marcellin',           'piece', 'cremerie'),
  ('Mimolette',                 'g',     'cremerie'),
  ('Gouda',                     'g',     'cremerie'),
  ('Edam',                      'g',     'cremerie'),
  ('Grana Padano',              'g',     'cremerie'),
  ('Pecorino',                  'g',     'cremerie'),
  ('Halloumi',                  'g',     'cremerie'),
  ('Tête de moine',             'g',     'cremerie'),
  ('Vacherin',                  'g',     'cremerie'),

  -- Pâtes (types) — feuilletée/brisée/pizza sont déjà en 081
  ('Pâte sablée',               'piece', 'boulangerie'),
  ('Pâte sucrée',               'piece', 'boulangerie'),
  ('Pâte à tarte',              'piece', 'boulangerie'),
  ('Pâte filo',                 'piece', 'boulangerie'),
  ('Feuille de brick',          'piece', 'boulangerie'),
  ('Pâte à crêpes',             'ml',    'boulangerie'),
  ('Pâte à choux',              'g',     'boulangerie'),
  ('Pâte à pain',               'g',     'boulangerie'),
  ('Pâte à crumble',            'g',     'boulangerie'),

  -- Fruits frais (round 2)
  ('Mûre',                      'g',     'fruits'),
  ('Groseille',                 'g',     'fruits'),
  ('Cassis',                    'g',     'fruits'),
  ('Grenade',                   'piece', 'fruits'),
  ('Litchi',                    'g',     'fruits'),
  ('Fruit de la passion',       'piece', 'fruits'),
  ('Papaye',                    'piece', 'fruits'),
  ('Goyave',                    'piece', 'fruits'),
  ('Nectarine',                 'piece', 'fruits'),
  ('Brugnon',                   'piece', 'fruits'),
  ('Mandarine',                 'piece', 'fruits'),
  ('Pomelo',                    'piece', 'fruits'),
  ('Coing',                     'piece', 'fruits'),
  ('Rhubarbe',                  'g',     'fruits'),
  ('Mirabelle',                 'g',     'fruits'),
  ('Reine-claude',              'g',     'fruits'),
  ('Kaki',                      'piece', 'fruits'),
  ('Physalis',                  'g',     'fruits'),
  ('Carambole',                 'piece', 'fruits'),

  -- Sauces & condiments (round 2)
  ('Sauce barbecue',            'ml',    'epicerie_salee'),
  ('Sauce burger',              'ml',    'epicerie_salee'),
  ('Sauce samouraï',            'ml',    'epicerie_salee'),
  ('Sauce algérienne',          'ml',    'epicerie_salee'),
  ('Sauce blanche',             'ml',    'epicerie_salee'),
  ('Sauce aigre-douce',         'ml',    'epicerie_salee'),
  ('Sauce nuoc-mâm',            'ml',    'epicerie_salee'),
  ('Sauce d''huître',           'ml',    'epicerie_salee'),
  ('Sauce hoisin',              'g',     'epicerie_salee'),
  ('Sauce teriyaki',            'ml',    'epicerie_salee'),
  ('Sauce sriracha',            'ml',    'epicerie_salee'),
  ('Tabasco',                   'ml',    'epicerie_salee'),
  ('Harissa',                   'g',     'epicerie_salee'),
  ('Sauce béchamel',            'ml',    'epicerie_salee'),
  ('Sauce tartare',             'g',     'epicerie_salee'),
  ('Sauce cocktail',            'g',     'epicerie_salee'),
  ('Sauce César',               'ml',    'epicerie_salee'),
  ('Vinaigrette',               'ml',    'epicerie_salee'),
  ('Salsa',                     'g',     'epicerie_salee'),
  ('Sauce curry',               'ml',    'epicerie_salee'),
  ('Sauce satay',               'g',     'epicerie_salee'),
  ('Moutarde à l''ancienne',    'g',     'epicerie_salee'),
  ('Moutarde de Dijon',         'g',     'epicerie_salee'),
  ('Sauce poivre',              'ml',    'epicerie_salee'),
  ('Sauce soja sucrée',         'ml',    'epicerie_salee'),
  ('Coulis de tomate',          'ml',    'epicerie_salee')
on conflict do nothing;
